### PR TITLE
chore: Remove dependabot in favor of renovate

### PR DESCRIPTION
**Pull request by lordrip**
## Purpose
With the introduction of renovate, we need to disable dependabot.

### CODE REVIEW

**Comment by apupier** [comment]
How can I check that Renovate is in place and is able to replace the current dependabot config?

**Comment by lordrip** [comment]
> How can I check that Renovate is in place and is able to replace the current dependabot config?

You can check the open pull requests and notice that we have 2 dependency-related  providers
image

**Comment by apupier** [comment]
The 2 Pull Request are very different.

Renovate is acting only on the lock file, which sounds nasty at first sight as the version in the package.json won't be tested anymore.

**Comment by apupier** [comment]
> The 2 Pull Request are very different.
> 
> Renovate is acting only on the lock file, which sounds nasty at first sight as the version in the package.json won't be tested anymore.

and in fcact there is another Renovate [PR](https://github.com/KaotoIO/step-extension-repository/pull/961) which is similar to the one provided

**Review by igarashitm — APPROVED** [review]
Not sure why renovate created 2 separate PRs, but it looks like this typescript update is an exception, it's doing better than dependabot already in kaoto-ui, and dashboard looks nice

**Pull request merged**
